// packages/client/src/components/dialogs/MarkdownExportDialog.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { Check, ClipboardCopy } from "lucide-vue-next";
import Button from "@/components/Button.vue";
import Dialog from "@/components/dialogs/Dialog.vue";
import DialogHeader from "@/components/dialogs/DialogHeader.vue";
import DialogFooter from "@/components/dialogs/DialogFooter.vue";
import DialogTitle from "@/components/dialogs/DialogTitle.vue";
import DialogDescription from "@/components/dialogs/DialogDescription.vue";

interface TimerEntry {
  text: string;
  timestamp: string;
  mode?: "submit" | "typing-start";
}

const props = defineProps<{
  open: boolean;
  entries: TimerEntry[];
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
}>();

const copied = ref(false);

function formatMode(mode?: "submit" | "typing-start"): string {
  if (mode === "typing-start") return "Typing Start";
  if (mode === "submit") return "Submit";
  return "";
}

const markdown = computed(() => {
  if (props.entries.length === 0) return "";
  const hasMode = props.entries.some(entry => entry.mode !== undefined);
  if (hasMode) {
    const header = "| Text | Timestamp | Mode |";
    const separator = "| --- | --- | --- |";
    const rows = props.entries.map(entry => `| ${entry.text} | ${entry.timestamp} | ${formatMode(entry.mode)} |`);
    return [header, separator, ...rows].join("\n");
  }
  const header = "| Text | Timestamp |";
  const separator = "| --- | --- |";
  const rows = props.entries.map(entry => `| ${entry.text} | ${entry.timestamp} |`);
  return [header, separator, ...rows].join("\n");
});

async function handleCopy() {
  await navigator.clipboard.writeText(markdown.value);
  copied.value = true;
  setTimeout(() => { copied.value = false; }, 2000);
}

function handleOpenChange(value: boolean) {
  emit("update:open", value);
  if (!value) {
    copied.value = false;
  }
}
</script>

<template>
  <Dialog
    :open="props.open"
    @update:open="handleOpenChange"
  >
    <DialogHeader>
      <DialogTitle data-testid="export-markdown-title">
        Export as Markdown
      </DialogTitle>
      <DialogDescription data-testid="export-markdown-description">
        Copy the markdown below to use your entries elsewhere.
      </DialogDescription>
    </DialogHeader>
    <textarea
      readonly
      :value="markdown"
      class="h-48 w-full resize-none rounded-md border bg-muted px-3 py-2 font-mono text-sm focus:ring-2 focus:ring-ring focus:outline-none"
      data-testid="markdown-export-textarea"
    />
    <DialogFooter>
      <Button
        data-testid="copy-markdown-button"
        @click="handleCopy"
      >
        <Check
          v-if="copied"
          class="size-4"
        />
        <ClipboardCopy
          v-else
          class="size-4"
        />
        {{ copied ? "Copied!" : "Copy to Clipboard" }}
      </Button>
    </DialogFooter>
  </Dialog>
</template>

// packages/client/src/components/MarkdownExportDialog.tsx
import { useCallback, useRef, useState } from "react";

import { Check, ClipboardCopy } from "lucide-react";

import { Button } from "@/components/Button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/Dialog";

interface TimerEntry {
  text: string;
  timestamp: string;
  mode?: "submit" | "typing-start";
}

interface MarkdownExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  entries: TimerEntry[];
}

function formatMode(mode?: "submit" | "typing-start"): string {
  if (mode === "typing-start") return "Typing Start";
  if (mode === "submit") return "Submit";
  return "";
}

function entriesToMarkdown(entries: TimerEntry[]): string {
  if (entries.length === 0) {
    return "";
  }

  const hasMode = entries.some(entry => entry.mode !== undefined);

  if (hasMode) {
    const header = "| Text | Timestamp | Mode |";
    const separator = "| --- | --- | --- |";
    const rows = entries.map(entry => `| ${entry.text} | ${entry.timestamp} | ${formatMode(entry.mode)} |`);
    return [header, separator, ...rows].join("\n");
  }

  const header = "| Text | Timestamp |";
  const separator = "| --- | --- |";
  const rows = entries.map(entry => `| ${entry.text} | ${entry.timestamp} |`);

  return [header, separator, ...rows].join("\n");
}

export function MarkdownExportDialog({
  open,
  onOpenChange,
  entries,
}: MarkdownExportDialogProps) {
  const [copied, setCopied] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const markdown = entriesToMarkdown(entries);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [markdown]);

  return (
    <Dialog
      open={open}
      onOpenChange={(value) => {
        onOpenChange(value);
        if (!value) {
          setCopied(false);
        }
      }}
    >
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Export as Markdown</DialogTitle>
          <DialogDescription>
            Copy the markdown below to use your entries elsewhere.
          </DialogDescription>
        </DialogHeader>
        <textarea
          ref={textareaRef}
          readOnly
          value={markdown}
          className={`
            h-48 w-full resize-none rounded-md border bg-muted px-3 py-2
            font-mono text-sm
            focus:ring-2 focus:ring-ring focus:outline-none
          `}
          data-testid="markdown-export-textarea"
        />
        <DialogFooter>
          <Button
            onClick={handleCopy}
            data-testid="copy-markdown-button"
          >
            {copied
              ? (
                <>
                  <Check className="size-4" />
                  Copied!
                </>
              )
              : (
                <>
                  <ClipboardCopy className="size-4" />
                  Copy to Clipboard
                </>
              )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
