// packages/client/src/components/Timer.vue
<script setup lang="ts">
import { ref, onUnmounted } from "vue";
import Button from "@/components/Button.vue";
import { formatTime } from "@/utils/formatTime";

const emit = defineEmits<{
  tick: [elapsedMs: number];
  runningChange: [isRunning: boolean];
}>();

const elapsedMs = ref(0);
const isRunning = ref(false);
let intervalId: ReturnType<typeof setInterval> | null = null;
let startTime = 0;

function start() {
  if (isRunning.value) return;
  isRunning.value = true;
  emit("runningChange", true);
  startTime = Date.now() - elapsedMs.value;
  intervalId = setInterval(() => {
    const newElapsed = Date.now() - startTime;
    elapsedMs.value = newElapsed;
    emit("tick", newElapsed);
  }, 10);
}

function stop() {
  if (!isRunning.value) return;
  isRunning.value = false;
  emit("runningChange", false);
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
}

function reset() {
  isRunning.value = false;
  emit("runningChange", false);
  elapsedMs.value = 0;
  emit("tick", 0);
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
}

onUnmounted(() => {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
});
</script>

<template>
  <div
    class="flex flex-col items-center gap-6"
    data-testid="timer-component-root"
  >
    <div
      class="font-mono text-5xl font-bold tracking-tight tabular-nums"
      data-testid="timer-display"
    >
      {{ formatTime(elapsedMs) }}
    </div>
    <div class="flex gap-3">
      <Button
        v-if="!isRunning"
        data-testid="timer-start-button"
        @click="start"
      >
        Start Timer
      </Button>
      <Button
        v-if="isRunning"
        data-testid="timer-stop-button"
        @click="stop"
      >
        Stop Timer
      </Button>
      <Button
        v-if="elapsedMs > 0"
        variant="destructive"
        data-testid="timer-reset-button"
        @click="reset"
      >
        Reset Timer
      </Button>
    </div>
  </div>
</template>

// packages/client/src/components/Timer.tsx
import { useState, useRef, useCallback, useEffect } from "react";

import { Button } from "@/components/Button";
import { formatTime } from "@/utils/formatTime";

interface TimerProps {

  onTick?: (elapsedMs: number) => void;

  onRunningChange?: (isRunning: boolean) => void;
}

export function Timer({
  onTick,
  onRunningChange,
}: TimerProps) {
  const [elapsedMs, setElapsedMs] = useState(0);
  const [isRunning, setIsRunning] = useState(false);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const startTimeRef = useRef<number>(0);
  const onTickRef = useRef(onTick);
  onTickRef.current = onTick;
  const onRunningChangeRef = useRef(onRunningChange);
  onRunningChangeRef.current = onRunningChange;

  const start = useCallback(() => {
    if (isRunning) return;
    setIsRunning(true);
    onRunningChangeRef.current?.(true);
    startTimeRef.current = Date.now() - elapsedMs;
    intervalRef.current = setInterval(() => {
      const newElapsed = Date.now() - startTimeRef.current;
      setElapsedMs(newElapsed);
      onTickRef.current?.(newElapsed);
    }, 10);
  }, [isRunning, elapsedMs]);

  const stop = useCallback(() => {
    if (!isRunning) return;
    setIsRunning(false);
    onRunningChangeRef.current?.(false);
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
  }, [isRunning]);

  useEffect(() => {
    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
    };
  }, []);

  const reset = useCallback(() => {
    setIsRunning(false);
    onRunningChangeRef.current?.(false);
    setElapsedMs(0);
    onTickRef.current?.(0);
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
  }, []);

  return (
    <div
      className="flex flex-col items-center gap-6"
      data-testid="timer-component-root"
    >
      <div
        className="font-mono text-5xl font-bold tracking-tight tabular-nums"
        data-testid="timer-display"
      >
        {formatTime(elapsedMs)}
      </div>
      <div className="flex gap-3">
        {!isRunning && (
          <Button
            onClick={start}
            data-testid="timer-start-button"
          >
            Start Timer
          </Button>
        )}
        {isRunning && (
          <Button
            onClick={stop}
            data-testid="timer-stop-button"
          >
            Stop Timer
          </Button>
        )}
        {elapsedMs > 0 && (
          <Button
            onClick={reset}
            variant="destructive"
            data-testid="timer-reset-button"
          >
            Reset Timer
          </Button>
        )}
      </div>
    </div>
  );
}
